// Generated by scripts/gen_prot_tables.py from MAME vamphalf_prot.cpp. Do not edit.
// Entry e: seed values first (value 0 in the top bits), the result in the low 8 bits.

function automatic [71:0] vh_prot_t8(input [2:0] e);
	case (e)
		3'd0: vh_prot_t8 = 72'h806b4bfbe3fb55f6f0;
		3'd1: vh_prot_t8 = 72'hdf7c1de18701be31e0;
		3'd2: vh_prot_t8 = 72'h57730e4767678758a0;
		3'd3: vh_prot_t8 = 72'h893c59ea57127bd200;
		3'd4: vh_prot_t8 = 72'ha1d83c54542f36af80;
		3'd5: vh_prot_t8 = 72'h5fd8988e1f3f37ee20;
		default: vh_prot_t8 = 72'hda037899cde21b7790;
	endcase
endfunction

function automatic [135:0] vh_prot_t16(input [0:0] e);
	case (e)
		1'd0: vh_prot_t16 = 136'h4d4dfabea65aa4868edc092d4eef56e1a0;
		default: vh_prot_t16 = 136'hd9d98f5f3fb6eec3f84d0deabea6da64c0;
	endcase
endfunction

function automatic [263:0] vh_prot_tw(input [3:0] e);
	case (e)
		4'd0: vh_prot_tw = 264'h53dc270456640daa421e3eac4d1c2f5a20da2fe469ac161a261e525e65127e7000;
		4'd1: vh_prot_tw = 264'h167e2781446a794a15fa59e21cfa3f550ff70abd31de237c2f1c7de14487620008;
		4'd2: vh_prot_tw = 264'h592027fe327264ec69d675186cd94f4f7f1365947a1230dc381b296323fc45920f;
		4'd3: vh_prot_tw = 264'h1bc2287d2078508e3db4104d3cb65f496e2e406d42463e3d411854e4037129250d;
		4'd4: vh_prot_tw = 264'h5e6628fa0e7e3c2e11902b830c956f435d4a1b440a784b9d4a17006662e40cb50e;
		4'd5: vh_prot_tw = 264'h210829797c8427d0656d46b85c727f3c4c69761d52ac58fd53152be9425970470e;
		4'd6: vh_prot_tw = 264'h63aa29f66a8c1372394961ec2c510f363b8550f41adf665e5c14576b21cf53d80c;
		4'd7: vh_prot_tw = 264'h264e2a7558927f120d257d237c2e1f302aa02bcd631373be651302ed014237680a;
		4'd8: vh_prot_tw = 264'h68f02af246986ab4610118574c0d2f2a19bc06a42b47011f6e102e6e60b71afa0c;
		4'd9: vh_prot_tw = 264'h2b922b6f349e565634df338d1beb3f2508d9617d73790e7f770f59f0402a7e8a07;
		default: vh_prot_tw = 264'h6e362bec22a641f708ba4ec26bc84f1f77f73c543bad1be1000d05731fa1621d03;
	endcase
endfunction
