#!/usr/bin/env python3
"""Generate rtl/vh_prot_tables.svh from MAME's vamphalf_prot.cpp (the seed tables, transcribed by
program so that no value is typed by hand).

    python scripts/gen_prot_tables.py [--mame E:/mame]
"""
import argparse
import pathlib
import re

REPO = pathlib.Path(__file__).resolve().parent.parent


def tables(src):
    out = {}
    for name in ("prot_table_8", "prot_table_16", "prot_table"):
        m = re.search(r"std::vector<std::vector<u(?:8|16)>>\s+" + name + r"\s*=\s*\{(.*?)\n\s*\};", src, re.S)
        assert m, name
        body = re.sub(r"//[^\n]*", "", m.group(1))
        rows = re.findall(r"\{([^{}]*)\}", body)
        out[name] = [[int(v, 16) for v in re.findall(r"0x[0-9a-fA-F]+", r)] for r in rows]
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--mame", default="E:/mame")
    a = ap.parse_args()
    src = (pathlib.Path(a.mame) / "src/mame/misc/vamphalf_prot.cpp").read_text(encoding="utf-8")
    t = tables(src)
    t8, t16, tw = t["prot_table_8"], t["prot_table_16"], t["prot_table"]
    assert len(t8) == 7 and all(len(r) == 9 for r in t8)
    assert len(t16) == 2 and all(len(r) == 17 for r in t16)
    assert len(tw) == 11 and all(len(r) == 17 for r in tw)

    L = ["// Generated by scripts/gen_prot_tables.py from MAME vamphalf_prot.cpp. Do not edit.",
         "// Entry e: seed values first (value 0 in the top bits), the result in the low 8 bits.", ""]

    def func(name, rows, n, w, ew):
        bits = n * w + 8
        L.append(f"function automatic [{bits - 1}:0] {name}(input [{ew - 1}:0] e);")
        L.append("\tcase (e)")
        for i, r in enumerate(rows):
            hexs = "".join(f"{v:0{w // 4}x}" for v in r[:n]) + f"{r[n]:02x}"
            label = "default" if i == len(rows) - 1 else f"{ew}'d{i}"
            L.append(f"\t\t{label}: {name} = {bits}'h{hexs};")
        L.append("\tendcase")
        L.append("endfunction")
        L.append("")

    func("vh_prot_t8", t8, 8, 8, 3)
    func("vh_prot_t16", t16, 16, 8, 1)
    func("vh_prot_tw", tw, 16, 16, 4)
    out = REPO / "rtl" / "vh_prot_tables.svh"
    out.write_text("\n".join(L), encoding="utf-8", newline="\n")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
